<a href="https://colab.research.google.com/github/Navegantes-UNIVESP/PI4_SIM/blob/main/PI4_SIM_Relat%C3%B3rio_Parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dados do SIM (Sistema de Informações de Mortalidade)
Fonte: https://opendatasus.saude.gov.br/dataset/sim-2020-2021

In [ ]:
import pandas as pd

url="https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIM/DO21OPEN.csv"
df = pd.read_csv(url, sep=";")

<ipython-input-1-f8fe2b5ed14e>:4: DtypeWarning: Columns (65,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url, sep=";")

In [ ]:
#Mostrar todas as colunas
pd.set_option('display.max_columns', None)

In [ ]:
df.head()

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC,ESC2010,SERIESCFAL,OCUP,CODMUNRES,LOCOCOR,CODESTAB,CODMUNOCOR,IDADEMAE,ESCMAE,ESCMAE2010,SERIESCMAE,OCUPMAE,QTDFILVIVO,QTDFILMORT,GRAVIDEZ,SEMAGESTAC,GESTACAO,PARTO,OBITOPARTO,PESO,TPMORTEOCO,OBITOGRAV,OBITOPUERP,ASSISTMED,EXAME,CIRURGIA,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,CAUSABAS,CB_PRE,COMUNSVOIM,DTATESTADO,CIRCOBITO,ACIDTRAB,FONTE,NUMEROLOTE,DTINVESTIG,DTCADASTRO,ATESTANTE,STCODIFICA,CODIFICADO,VERSAOSIST,VERSAOSCB,FONTEINV,DTRECEBIM,ATESTADO,DTRECORIGA,OPOR_DO,CAUSAMAT,ESCMAEAGR1,ESCFALAGR1,STDOEPIDEM,STDONOVA,DIFDATA,NUDIASOBCO,DTCADINV,TPOBITOCOR,DTCONINV,FONTES,TPRESGINFO,TPNIVELINV,DTCADINF,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT
0,1,1,2,13042021,611.0,831.0,317190.0,25051955.0,465.0,1,4.0,2.0,NaN,NaN,NaN,621005.0,110028,1,213837.0,110020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,*J960,*B342*U071,*J988,NaN,NaN,B342,NaN,NaN,13042021.0,NaN,NaN,NaN,20210062.0,NaN,13042021.0,1.0,S,S,3.2.30,3.3,NaN,14042021.0,J960/B342 U071/J988,14042021,1,NaN,NaN,NaN,0.0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B342,N,NaN,NaN
1,2,1,2,13042021,200.0,841.0,412730.0,8091956.0,464.0,1,4.0,1.0,3.0,2.0,NaN,999993.0,110020,1,2515369.0,110020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,*A419,*R579,*J189,*B342*U071,NaN,B342,NaN,NaN,13042021.0,NaN,NaN,NaN,20210063.0,NaN,13042021.0,2.0,S,S,3.2.30,3.3,NaN,15042021.0,A419/R579/J189/B342 U071,14042021,1,NaN,NaN,11.0,0.0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B342,N,NaN,NaN
2,3,1,2,12042021,2238.0,811.0,110020.0,7121972.0,448.0,1,2.0,2.0,5.0,5.0,NaN,223505.0,110020,1,213837.0,110020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,*J960,*B342*U071,NaN,NaN,*E119,B342,NaN,NaN,12042021.0,NaN,NaN,NaN,20210067.0,NaN,13042021.0,1.0,S,S,3.2.30,3.3,NaN,22042021.0,J960/B342 U071*E119,14042021,2,NaN,NaN,8.0,0.0,1,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B342,N,NaN,NaN
3,4,1,2,25022021,2235.0,811.0,110020.0,12061964.0,456.0,2,4.0,2.0,4.0,3.0,3.0,999994.0,110020,1,2515458.0,110020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,1.0,NaN,NaN,2.0,*R578,*A419,*C780*C787,*C189,*N170*K729,C189,NaN,NaN,25022021.0,NaN,NaN,NaN,20210062.0,NaN,13042021.0,1.0,S,S,3.2.30,3.3,NaN,14042021.0,R578/A419/C780 C787/C189*N170 K729,14042021,48,NaN,NaN,6.0,0.0,1,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C189,N,NaN,NaN
4,5,1,2,12042021,1430.0,811.0,110004.0,6041983.0,438.0,2,4.0,NaN,NaN,NaN,NaN,NaN,110004,1,2515369.0,110020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,*J960,*B342*U071,*J189,*R092,NaN,B342,NaN,NaN,12042021.0,NaN,NaN,NaN,20210066.0,NaN,13042021.0,NaN,S,S,3.2.30,3.3,NaN,20042021.0,J960/B342 U071/J189/R092,14042021,2,NaN,NaN,NaN,0.0,1,8,0.0,11052021.0,9.0,12042021.0,NaN,NaN,M,NaN,NaN,NaN,NaN,B342,N,NaN,NaN

In [ ]:
df.shape

(1855622, 86)

In [ ]:
df.describe

<bound method NDFrame.describe of          contador  ORIGEM  TIPOBITO   DTOBITO  HORAOBITO  NATURAL  CODMUNNATU  \
0               1       1         2  13042021      611.0    831.0    317190.0
1               2       1         2  13042021      200.0    841.0    412730.0
2               3       1         2  12042021     2238.0    811.0    110020.0
3               4       1         2  25022021     2235.0    811.0    110020.0
4               5       1         2  12042021     1430.0    811.0    110004.0
...           ...     ...       ...       ...        ...      ...         ...
1855617   1855618       1         2   7122021        NaN    813.0    130030.0
1855618   1855619       1         2  26102021        NaN    813.0    130250.0
1855619   1855620       1         2   4112021      200.0    813.0    130140.0
1855620   1855621       1         1   1122021     1000.0    813.0    130270.0
1855621   1855622       1         2  11102021        NaN      NaN         NaN

             DTNASC  IDADE  SEXO  RACACOR  ESTCIV  ESC  ESC2010  SERIESCFAL  \
0        25051955.0  465.0     1      4.0     2.0  NaN      NaN         NaN
1         8091956.0  464.0     1      4.0     1.0  3.0      2.0         NaN
2         7121972.0  448.0     1      2.0     2.0  5.0      5.0         NaN
3        12061964.0  456.0     2      4.0     2.0  4.0      3.0         3.0
4         6041983.0  438.0     2      4.0     NaN  NaN      NaN         NaN
...             ...    ...   ...      ...     ...  ...      ...         ...
1855617  16031940.0  481.0     2      5.0     NaN  9.0      9.0         NaN
1855618  24072019.0  402.0     2      5.0     NaN  NaN      NaN         NaN
1855619   4091949.0  472.0     1      5.0     NaN  1.0      0.0         NaN
1855620         NaN    NaN     1      5.0     NaN  NaN      NaN         NaN
1855621  28032021.0  306.0     1      5.0     NaN  NaN      NaN         NaN

             OCUP  CODMUNRES  LOCOCOR   CODESTAB  CODMUNOCOR  IDADEMAE  \
0        621005.0     110028        1   213837.0      110020       NaN
1        999993.0     110020        1  2515369.0      110020       NaN
2        223505.0     110020        1   213837.0      110020       NaN
3        999994.0     110020        1  2515458.0      110020       NaN
4             NaN     110004        1  2515369.0      110020       NaN
...           ...        ...      ...        ...         ...       ...
1855617       NaN     130030        6        NaN      130030       NaN
1855618       NaN     130063        5        NaN      130063       NaN
1855619       NaN     130140        6        NaN      130140       NaN
1855620       NaN     130270        6        NaN      130170      38.0
1855621       NaN     120034        6        NaN      120034       NaN

         ESCMAE  ESCMAE2010  SERIESCMAE  OCUPMAE  QTDFILVIVO  QTDFILMORT  \
0           NaN         NaN         NaN      NaN         NaN         NaN
1           NaN         NaN         NaN      NaN         NaN         NaN
2           NaN         NaN         NaN      NaN         NaN         NaN
3           NaN         NaN         NaN      NaN         NaN         NaN
4           NaN         NaN         NaN      NaN         NaN         NaN
...         ...         ...         ...      ...         ...         ...
1855617     NaN         NaN         NaN      NaN         NaN         NaN
1855618     NaN         NaN         NaN      NaN         NaN         NaN
1855619     NaN         NaN         NaN      NaN         NaN         NaN
1855620     1.0         0.0         NaN      NaN         8.0         0.0
1855621     NaN         NaN         NaN      NaN         NaN         NaN

         GRAVIDEZ  SEMAGESTAC  GESTACAO  PARTO  OBITOPARTO  PESO  TPMORTEOCO  \
0             NaN         NaN       NaN    NaN         NaN   NaN         NaN
1             NaN         NaN       NaN    NaN         NaN   NaN         NaN
2             NaN         NaN       NaN    NaN         NaN   NaN         NaN
3             NaN         NaN       NaN    NaN         NaN   NaN         9.0
4             NaN         NaN       NaN    NaN         NaN   NaN         NaN
...           ...         ...       ...    ...         ...   ...         ...
1855617       NaN         NaN       NaN    NaN         NaN   NaN         NaN
1855618       NaN         NaN       NaN    NaN         NaN   NaN         NaN
1855619       NaN         NaN       NaN    NaN         NaN   NaN         NaN
1855620       1.0         NaN       NaN    1.0         1.0   NaN         NaN
1855621       NaN         NaN       NaN    NaN         NaN   NaN         NaN

         OBITOGRAV  OBITOPUERP  ASSISTMED  EXAME  CIRURGIA  NECROPSIA LINHAA  \
0              NaN         NaN        1.0    NaN       NaN        NaN  *J960
1              NaN         NaN        1.0    NaN       NaN        2.0  *A419
2              NaN         NaN        1.0    NaN       NaN        NaN  *J960
3              9.0         9.0        1.0    NaN       NaN        2.0  *R578
4              NaN         NaN        1.0    NaN       NaN        NaN  *J960
...            ...         ...        ...    ...       ...        ...    ...
1855617        NaN         NaN        NaN    NaN       NaN        NaN  *R99X
1855618        NaN         NaN        NaN    NaN       NaN        NaN  *R98X
1855619        NaN         NaN        NaN    NaN       NaN        NaN  *R98X
1855620        NaN         NaN        NaN    NaN       NaN        NaN  *P95X
1855621        NaN         NaN        2.0    NaN       NaN        2.0  *R99X

             LINHAB      LINHAC      LINHAD     LINHAII CAUSABAS  CB_PRE  \
0        *B342*U071       *J988         NaN         NaN     B342     NaN
1             *R579       *J189  *B342*U071         NaN     B342     NaN
2        *B342*U071         NaN         NaN       *E119     B342     NaN
3             *A419  *C780*C787       *C189  *N170*K729     C189     NaN
4        *B342*U071       *J189       *R092         NaN     B342     NaN
...             ...         ...         ...         ...      ...     ...
1855617         NaN         NaN         NaN  *I10X*E149      I10     NaN
1855618         NaN         NaN         NaN         NaN      R98     NaN
1855619         NaN         NaN         NaN         NaN      R98     NaN
1855620         NaN         NaN         NaN         NaN      P95     NaN
1855621         NaN         NaN         NaN         NaN      R99     NaN

         COMUNSVOIM  DTATESTADO  CIRCOBITO  ACIDTRAB  FONTE  NUMEROLOTE  \
0               NaN  13042021.0        NaN       NaN    NaN  20210062.0
1               NaN  13042021.0        NaN       NaN    NaN  20210063.0
2               NaN  12042021.0        NaN       NaN    NaN  20210067.0
3               NaN  25022021.0        NaN       NaN    NaN  20210062.0
4               NaN  12042021.0        NaN       NaN    NaN  20210066.0
...             ...         ...        ...       ...    ...         ...
1855617         NaN  10012022.0        NaN       NaN    NaN         NaN
1855618         NaN         NaN        NaN       NaN    NaN         NaN
1855619         NaN  29112021.0        NaN       NaN    NaN         NaN
1855620         NaN         NaN        NaN       NaN    NaN         NaN
1855621         NaN  11102021.0        NaN       NaN    NaN         NaN

         DTINVESTIG  DTCADASTRO  ATESTANTE STCODIFICA CODIFICADO VERSAOSIST  \
0               NaN  13042021.0        1.0          S          S     3.2.30
1               NaN  13042021.0        2.0          S          S     3.2.30
2               NaN  13042021.0        1.0          S          S     3.2.30
3               NaN  13042021.0        1.0          S          S     3.2.30
4               NaN  13042021.0        NaN          S          S     3.2.30
...             ...         ...        ...        ...        ...        ...
1855617         NaN  15032022.0        NaN          N          N      2...0
1855618         NaN  15032022.0        NaN          N          N      2...0
1855619  26112021.0  28012022.0        5.0          N          N      2...0
1855620         NaN  15032022.0        NaN          N          N      2...0
1855621  15102021.0  14122021.0        5.0          N          N      2...0

         VERSAOSCB  FONTEINV   DTRECEBIM                            ATESTADO  \
0              3.3       NaN  14042021.0                 J960/B342 U071/J988
1              3.3       NaN  15042021.0            A419/R579/J189/B342 U071
2              3.3       NaN  22042021.0                 J960/B342 U071*E119
3              3.3       NaN  14042021.0  R578/A419/C780 C787/C189*N170 K729
4              3.3       NaN  20042021.0            J960/B342 U071/J189/R092
...            ...       ...         ...                                 ...
1855617        NaN       NaN         NaN                        R99*I10 E149
1855618        NaN       NaN         NaN                                 R98
1855619        NaN       2.0         NaN                                 R98
1855620        NaN       NaN         NaN                                 P95
1855621        NaN       2.0         NaN                                 R99

         DTRECORIGA  OPOR_DO CAUSAMAT  ESCMAEAGR1  ESCFALAGR1  STDOEPIDEM  \
0          14042021        1      NaN         NaN         NaN         0.0
1          14042021        1      NaN         NaN        11.0         0.0
2          14042021        2      NaN         NaN         8.0         0.0
3          14042021       48      NaN         NaN         6.0         0.0
4          14042021        2      NaN         NaN         NaN         0.0
...             ...      ...      ...         ...         ...         ...
1855617    15032022       98      NaN         NaN         9.0         0.0
1855618    15032022      140      NaN         NaN         NaN         0.0
1855619    28012022       85      NaN         NaN         0.0         0.0
1855620    15032022      104      NaN         0.0         NaN         0.0
1855621    14122021       64      NaN         NaN         NaN         0.0

         STDONOVA  DIFDATA  NUDIASOBCO    DTCADINV  TPOBITOCOR    DTCONINV  \
0               1        1         NaN         NaN         NaN         NaN
1               1        2         NaN         NaN         NaN         NaN
2               1       10         NaN         NaN         NaN         NaN
3               1       48         NaN         NaN         NaN         NaN
4               1        8         0.0  11052021.0         9.0  12042021.0
...           ...      ...         ...         ...         ...         ...
1855617         1       98         NaN         NaN         NaN         NaN
1855618         1      140         NaN         NaN         NaN         NaN
1855619         1       85         NaN         NaN         NaN         NaN
1855620         1      104         NaN         NaN         NaN         NaN
1855621         1       64         NaN         NaN         NaN         NaN

         FONTES  TPRESGINFO TPNIVELINV    DTCADINF  MORTEPARTO   DTCONCASO  \
0           NaN         NaN        NaN         NaN         NaN         NaN
1           NaN         NaN        NaN         NaN         NaN         NaN
2           NaN         NaN        NaN         NaN         NaN         NaN
3           NaN         NaN        NaN         NaN         NaN         NaN
4           NaN         NaN          M         NaN         NaN         NaN
...         ...         ...        ...         ...         ...         ...
1855617     NaN         NaN        NaN         NaN         NaN         NaN
1855618  SXXXXX         NaN        NaN  25032022.0         3.0  23032022.0
1855619     NaN         NaN        NaN         NaN         NaN         NaN
1855620  XXXXXX         NaN        NaN  16032022.0         1.0  16032022.0
1855621  SXXXXX         NaN        NaN  10032022.0         3.0         NaN

         ALTCAUSA CAUSABAS_O TPPOS  TP_ALTERA CB_ALT
0             NaN       B342     N        NaN    NaN
1             NaN       B342     N        NaN    NaN
2             NaN       B342     N        NaN    NaN
3             NaN       C189     N        NaN    NaN
4             NaN       B342     N        NaN    NaN
...           ...        ...   ...        ...    ...
1855617       NaN        NaN   NaN        NaN    NaN
1855618       1.0        NaN   NaN        NaN    NaN
1855619       NaN        NaN   NaN        NaN    NaN
1855620       1.0        NaN   NaN        NaN    NaN
1855621       1.0        NaN   NaN        NaN    NaN

[1855622 rows x 86 columns]>

In [ ]:
df_idade = df["IDADE"]

In [ ]:
df_idade.unique()

array([465., 464., 448., 456., 438., 467., 471., 487., 473., 496., 463.,
       460., 466., 474., 455., 441., 462., 485., 495., 478., 476., 484.,
       483., 461., 458., 459., 482., 486., 493., 470., 469., 477., 489.,
       435., 472., 457., 500., 418., 454., 453., 433., 428., 440., 449.,
       481., 468., 490., 447., 446., 444., 480.,  nan, 445., 439., 498.,
       443., 214., 452., 451., 436., 424., 201., 488., 479., 492., 491.,
       475., 427., 442., 494., 501., 408., 430., 420., 434., 103., 499.,
       497., 412., 205., 450., 302., 431., 425., 206., 504., 101., 437.,
       429., 203., 303., 311.,  45., 102.,  32., 426., 414., 502., 503.,
       208., 217., 432., 310., 305., 213., 301.,  44., 421., 419., 422.,
       407., 415., 423., 306., 403., 401., 209., 404., 413., 410., 417.,
       999., 204., 308., 221., 111., 416., 409., 210.,  20., 515., 505.,
       211., 411., 402., 207., 506., 215., 307., 202., 227.,  25., 106.,
       105., 220., 405.,  19., 200., 118., 219., 109., 104.,  22.,  46.,
       212., 110., 304.,  40., 115.,  26., 123., 228., 225., 223.,  24.,
       511., 516., 108.,  42., 508., 406., 112.,  37.,  10.,  30., 510.,
       509.,   5.,  50.,   1., 513.,  34., 119.,  15., 114.,  16.,   4.,
       216., 309., 121., 218., 107., 122., 116., 229., 113., 512., 514.,
        29., 507.,  54., 120., 117.,  55., 222.,  21., 226.,  28.,  47.,
        39.,  23.,   3.,   8.,  43., 100.,  35.,   2.,  36., 517.,  56.,
       224.,  12.,  51.,  31.,  27.,  53.,  17.,  59.,  58.,  13.,  18.,
         9.,  11.,  52.,   6.,  49.,  57.,  41.,  14.,  38.,  48.,  33.,
       400., 520., 522.,   7., 519., 518., 521., 524.])

In [ ]:
df_idade["IDADE"]%400

In [ ]:
df_idade_10 = df_idade.head(10)
df_idade_10

0    465.0
1    464.0
2    448.0
3    456.0
4    438.0
5    467.0
6    471.0
7    487.0
8    473.0
9    496.0
Name: IDADE, dtype: float64

In [ ]:
display(df.loc[df["IDADE"]>=500])

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC,ESC2010,SERIESCFAL,OCUP,CODMUNRES,LOCOCOR,CODESTAB,CODMUNOCOR,IDADEMAE,ESCMAE,ESCMAE2010,SERIESCMAE,OCUPMAE,QTDFILVIVO,QTDFILMORT,GRAVIDEZ,SEMAGESTAC,GESTACAO,PARTO,OBITOPARTO,PESO,TPMORTEOCO,OBITOGRAV,OBITOPUERP,ASSISTMED,EXAME,CIRURGIA,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,CAUSABAS,CB_PRE,COMUNSVOIM,DTATESTADO,CIRCOBITO,ACIDTRAB,FONTE,NUMEROLOTE,DTINVESTIG,DTCADASTRO,ATESTANTE,STCODIFICA,CODIFICADO,VERSAOSIST,VERSAOSCB,FONTEINV,DTRECEBIM,ATESTADO,DTRECORIGA,OPOR_DO,CAUSAMAT,ESCMAEAGR1,ESCFALAGR1,STDOEPIDEM,STDONOVA,DIFDATA,NUDIASOBCO,DTCADINV,TPOBITOCOR,DTCONINV,FONTES,TPRESGINFO,TPNIVELINV,DTCADINF,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT
60,61,1,2,2042021,2350.0,852.0,521380.0,11011921.0,500.0,1,4.0,3.0,2.0,1.0,NaN,622020.0,171488,1,2755165.0,170210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,*J969,*J81X,NaN,NaN,*N179*I517*J90X*I313,N179,NaN,NaN,2042021.0,NaN,NaN,NaN,20210027.0,NaN,5042021.0,5.0,S,S,3.2.30,3.3,NaN,3052021.0,J969/J81*N179 I517 J90 I313,8042021,6,NaN,NaN,10.0,0.0,1,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N179,NaN,NaN,NaN
168,169,1,2,16062021,1930.0,831.0,315780.0,14091920.0,500.0,2,4.0,2.0,2.0,1.0,NaN,141410.0,310620,1,6437745.0,310620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*J969,*J189,NaN,NaN,*I10X*E149,J189,NaN,NaN,16062021.0,NaN,NaN,NaN,20210030.0,NaN,22072021.0,2.0,S,S,3.2.30,3.4,NaN,28072021.0,J969/J189*I10 E149,28072021,42,NaN,NaN,10.0,0.0,1,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J189,N,NaN,NaN
243,244,1,2,22062021,1720.0,821.0,211250.0,10011920.0,501.0,2,4.0,3.0,1.0,0.0,NaN,999993.0,210090,1,2531798.0,210090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*J988*U049,NaN,NaN,NaN,NaN,J988,NaN,NaN,22062021.0,NaN,NaN,NaN,20210008.0,NaN,30062021.0,1.0,S,S,3.2.30,3.4,NaN,9072021.0,J988 U049,9072021,17,NaN,NaN,0.0,0.0,1,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U049,N,9.0,U049
374,375,1,2,27062021,1130.0,831.0,311610.0,12081919.0,501.0,2,4.0,3.0,1.0,0.0,NaN,999993.0,313545,3,NaN,313545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*R99X,*C449,NaN,NaN,NaN,C449,NaN,NaN,27062021.0,NaN,NaN,NaN,20210012.0,NaN,30072021.0,1.0,S,S,3.2.30,3.4,NaN,17082021.0,R99/C449,17082021,51,NaN,NaN,0.0,0.0,1,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C449,N,NaN,NaN
514,515,1,2,10022021,1352.0,831.0,313600.0,19091916.0,504.0,2,4.0,3.0,1.0,0.0,NaN,999993.0,315510,1,2139146.0,312560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*J960,*J189,NaN,NaN,NaN,J189,NaN,NaN,10022021.0,NaN,NaN,NaN,20210008.0,NaN,8072021.0,1.0,S,S,3.2.30,3.3,NaN,15072021.0,J960/J189,15072021,155,NaN,NaN,0.0,0.0,1,155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J189,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855260,1855261,2,2,17122021,1520.0,833.0,330480.0,8061919.0,502.0,2,4.0,3.0,2.0,1.0,NaN,999993.0,330455,3,NaN,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,*J960,*J988*U049,NaN,NaN,*I10X,J988,NaN,NaN,17122021.0,NaN,NaN,NaN,20210245.0,NaN,29122021.0,2.0,S,S,3.2.30,3.4,NaN,NaN,J960/J988 U049*I10,29122021,12,NaN,NaN,10.0,0.0,1,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855390,1855391,2,2,18122021,NaN,833.0,330000.0,NaN,999.0,1,4.0,9.0,9.0,9.0,NaN,NaN,330000,5,NaN,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*T179*Y208,NaN,NaN,NaN,NaN,Y208,NaN,330455.0,27122021.0,9.0,NaN,1.0,20210245.0,NaN,29122021.0,3.0,S,S,3.2.30,3.4,NaN,NaN,T179 Y208,29122021,11,NaN,NaN,9.0,0.0,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855402,1855403,2,2,10122021,931.0,NaN,NaN,2121920.0,501.0,2,1.0,4.0,1.0,0.0,NaN,999993.0,330455,2,5955645.0,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*A419,*J159,NaN,NaN,J159,NaN,NaN,10122021.0,NaN,NaN,NaN,20210245.0,NaN,29122021.0,5.0,S,S,3.2.30,3.4,NaN,NaN,/A419/J159,29122021,19,NaN,NaN,0.0,0.0,1,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855461,1855462,2,2,21122021,NaN,800.0,NaN,NaN,999.0,1,1.0,9.0,9.0,9.0,NaN,NaN,330000,5,NaN,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*R99X,NaN,NaN,NaN,NaN,R99,NaN,330455.0,22122021.0,NaN,NaN,NaN,20210245.0,NaN,30122021.0,3.0,S,S,3.2.30,3.4,NaN,NaN,R99,30122021,9,NaN,NaN,9.0,0.0,1,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855468,1855469,2,2,9122021,700.0,NaN,NaN,NaN,999.0,1,4.0,9.0,9.0,9.0,NaN,998999.0,330455,1,5717256.0,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*R570,*I269,NaN,NaN,NaN,I269,NaN,NaN,9122021.0,NaN,NaN,NaN,20210245.0,NaN,30122021.0,5.0,S,S,3.2.30,3.4,NaN,NaN,R570/I269,30122021,21,NaN,NaN,9.0,0.0,1,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[df["IDADE"]>=400]

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC,ESC2010,SERIESCFAL,OCUP,CODMUNRES,LOCOCOR,CODESTAB,CODMUNOCOR,IDADEMAE,ESCMAE,ESCMAE2010,SERIESCMAE,OCUPMAE,QTDFILVIVO,QTDFILMORT,GRAVIDEZ,SEMAGESTAC,GESTACAO,PARTO,OBITOPARTO,PESO,TPMORTEOCO,OBITOGRAV,OBITOPUERP,ASSISTMED,EXAME,CIRURGIA,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,CAUSABAS,CB_PRE,COMUNSVOIM,DTATESTADO,CIRCOBITO,ACIDTRAB,FONTE,NUMEROLOTE,DTINVESTIG,DTCADASTRO,ATESTANTE,STCODIFICA,CODIFICADO,VERSAOSIST,VERSAOSCB,FONTEINV,DTRECEBIM,ATESTADO,DTRECORIGA,OPOR_DO,CAUSAMAT,ESCMAEAGR1,ESCFALAGR1,STDOEPIDEM,STDONOVA,DIFDATA,NUDIASOBCO,DTCADINV,TPOBITOCOR,DTCONINV,FONTES,TPRESGINFO,TPNIVELINV,DTCADINF,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT
60,61,1,2,2042021,2350.0,852.0,521380.0,11011921.0,500.0,1,4.0,3.0,2.0,1.0,NaN,622020.0,171488,1,2755165.0,170210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,*J969,*J81X,NaN,NaN,*N179*I517*J90X*I313,N179,NaN,NaN,2042021.0,NaN,NaN,NaN,20210027.0,NaN,5042021.0,5.0,S,S,3.2.30,3.3,NaN,3052021.0,J969/J81*N179 I517 J90 I313,8042021,6,NaN,NaN,10.0,0.0,1,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N179,NaN,NaN,NaN
168,169,1,2,16062021,1930.0,831.0,315780.0,14091920.0,500.0,2,4.0,2.0,2.0,1.0,NaN,141410.0,310620,1,6437745.0,310620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*J969,*J189,NaN,NaN,*I10X*E149,J189,NaN,NaN,16062021.0,NaN,NaN,NaN,20210030.0,NaN,22072021.0,2.0,S,S,3.2.30,3.4,NaN,28072021.0,J969/J189*I10 E149,28072021,42,NaN,NaN,10.0,0.0,1,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J189,N,NaN,NaN
243,244,1,2,22062021,1720.0,821.0,211250.0,10011920.0,501.0,2,4.0,3.0,1.0,0.0,NaN,999993.0,210090,1,2531798.0,210090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*J988*U049,NaN,NaN,NaN,NaN,J988,NaN,NaN,22062021.0,NaN,NaN,NaN,20210008.0,NaN,30062021.0,1.0,S,S,3.2.30,3.4,NaN,9072021.0,J988 U049,9072021,17,NaN,NaN,0.0,0.0,1,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U049,N,9.0,U049
374,375,1,2,27062021,1130.0,831.0,311610.0,12081919.0,501.0,2,4.0,3.0,1.0,0.0,NaN,999993.0,313545,3,NaN,313545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*R99X,*C449,NaN,NaN,NaN,C449,NaN,NaN,27062021.0,NaN,NaN,NaN,20210012.0,NaN,30072021.0,1.0,S,S,3.2.30,3.4,NaN,17082021.0,R99/C449,17082021,51,NaN,NaN,0.0,0.0,1,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C449,N,NaN,NaN
514,515,1,2,10022021,1352.0,831.0,313600.0,19091916.0,504.0,2,4.0,3.0,1.0,0.0,NaN,999993.0,315510,1,2139146.0,312560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*J960,*J189,NaN,NaN,NaN,J189,NaN,NaN,10022021.0,NaN,NaN,NaN,20210008.0,NaN,8072021.0,1.0,S,S,3.2.30,3.3,NaN,15072021.0,J960/J189,15072021,155,NaN,NaN,0.0,0.0,1,155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J189,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855260,1855261,2,2,17122021,1520.0,833.0,330480.0,8061919.0,502.0,2,4.0,3.0,2.0,1.0,NaN,999993.0,330455,3,NaN,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,*J960,*J988*U049,NaN,NaN,*I10X,J988,NaN,NaN,17122021.0,NaN,NaN,NaN,20210245.0,NaN,29122021.0,2.0,S,S,3.2.30,3.4,NaN,NaN,J960/J988 U049*I10,29122021,12,NaN,NaN,10.0,0.0,1,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855390,1855391,2,2,18122021,NaN,833.0,330000.0,NaN,999.0,1,4.0,9.0,9.0,9.0,NaN,NaN,330000,5,NaN,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*T179*Y208,NaN,NaN,NaN,NaN,Y208,NaN,330455.0,27122021.0,9.0,NaN,1.0,20210245.0,NaN,29122021.0,3.0,S,S,3.2.30,3.4,NaN,NaN,T179 Y208,29122021,11,NaN,NaN,9.0,0.0,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855402,1855403,2,2,10122021,931.0,NaN,NaN,2121920.0,501.0,2,1.0,4.0,1.0,0.0,NaN,999993.0,330455,2,5955645.0,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*A419,*J159,NaN,NaN,J159,NaN,NaN,10122021.0,NaN,NaN,NaN,20210245.0,NaN,29122021.0,5.0,S,S,3.2.30,3.4,NaN,NaN,/A419/J159,29122021,19,NaN,NaN,0.0,0.0,1,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855461,1855462,2,2,21122021,NaN,800.0,NaN,NaN,999.0,1,1.0,9.0,9.0,9.0,NaN,NaN,330000,5,NaN,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*R99X,NaN,NaN,NaN,NaN,R99,NaN,330455.0,22122021.0,NaN,NaN,NaN,20210245.0,NaN,30122021.0,3.0,S,S,3.2.30,3.4,NaN,NaN,R99,30122021,9,NaN,NaN,9.0,0.0,1,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855468,1855469,2,2,9122021,700.0,NaN,NaN,NaN,999.0,1,4.0,9.0,9.0,9.0,NaN,998999.0,330455,1,5717256.0,330455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*R570,*I269,NaN,NaN,NaN,I269,NaN,NaN,9122021.0,NaN,NaN,NaN,20210245.0,NaN,30122021.0,5.0,S,S,3.2.30,3.4,NaN,NaN,R570/I269,30122021,21,NaN,NaN,9.0,0.0,1,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_idade_anos = df[(df["IDADE"]>=400) & (df["IDADE"]<500)]
df_idade_anos

Empty DataFrame
Columns: [contador, ORIGEM, TIPOBITO, DTOBITO, HORAOBITO, NATURAL, CODMUNNATU, DTNASC, IDADE, SEXO, RACACOR, ESTCIV, ESC, ESC2010, SERIESCFAL, OCUP, CODMUNRES, LOCOCOR, CODESTAB, CODMUNOCOR, IDADEMAE, ESCMAE, ESCMAE2010, SERIESCMAE, OCUPMAE, QTDFILVIVO, QTDFILMORT, GRAVIDEZ, SEMAGESTAC, GESTACAO, PARTO, OBITOPARTO, PESO, TPMORTEOCO, OBITOGRAV, OBITOPUERP, ASSISTMED, EXAME, CIRURGIA, NECROPSIA, LINHAA, LINHAB, LINHAC, LINHAD, LINHAII, CAUSABAS, CB_PRE, COMUNSVOIM, DTATESTADO, CIRCOBITO, ACIDTRAB, FONTE, NUMEROLOTE, DTINVESTIG, DTCADASTRO, ATESTANTE, STCODIFICA, CODIFICADO, VERSAOSIST, VERSAOSCB, FONTEINV, DTRECEBIM, ATESTADO, DTRECORIGA, OPOR_DO, CAUSAMAT, ESCMAEAGR1, ESCFALAGR1, STDOEPIDEM, STDONOVA, DIFDATA, NUDIASOBCO, DTCADINV, TPOBITOCOR, DTCONINV, FONTES, TPRESGINFO, TPNIVELINV, DTCADINF, MORTEPARTO, DTCONCASO, ALTCAUSA, CAUSABAS_O, TPPOS, TP_ALTERA, CB_ALT]
Index: []

In [ ]:
df.loc[(df["IDADE"]>400) & (df["IDADE"]<500), "IDADE"] = df["IDADE"]%400
df.IDADE.unique()

array([ 65.,  64.,  48.,  56.,  38.,  67.,  71.,  87.,  73.,  96.,  63.,
        60.,  66.,  74.,  55.,  41.,  62.,  85.,  95.,  78.,  76.,  84.,
        83.,  61.,  58.,  59.,  82.,  86.,  93.,  70.,  69.,  77.,  89.,
        35.,  72.,  57., 500.,  18.,  54.,  53.,  33.,  28.,  40.,  49.,
        81.,  68.,  90.,  47.,  46.,  44.,  80.,  nan,  45.,  39.,  98.,
        43., 214.,  52.,  51.,  36.,  24., 201.,  88.,  79.,  92.,  91.,
        75.,  27.,  42.,  94., 501.,   8.,  30.,  20.,  34., 103.,  99.,
        97.,  12., 205.,  50., 302.,  31.,  25., 206., 504., 101.,  37.,
        29., 203., 303., 311., 102.,  32.,  26.,  14., 502., 503., 208.,
       217., 310., 305., 213., 301.,  21.,  19.,  22.,   7.,  15.,  23.,
       306.,   3.,   1., 209.,   4.,  13.,  10.,  17., 999., 204., 308.,
       221., 111.,  16.,   9., 210., 515., 505., 211.,  11.,   2., 207.,
       506., 215., 307., 202., 227., 106., 105., 220.,   5., 200., 118.,
       219., 109., 104., 212., 110., 304., 115., 123., 228., 225., 223.,
       511., 516., 108., 508.,   6., 112., 510., 509., 513., 119., 114.,
       216., 309., 121., 218., 107., 122., 116., 229., 113., 512., 514.,
       507., 120., 117., 222., 226., 100., 517., 224.,   0., 520., 522.,
       519., 518., 521., 524.])